#39: replace variables.bat and variables with OS independent devon.properties

diff --git a/scripts/src/main/resources/scripts/environment-project b/scripts/src/main/resources/scripts/environment-project
--- a/scripts/src/main/resources/scripts/environment-project
+++ b/scripts/src/main/resources/scripts/environment-project
@@ -4,12 +4,29 @@
 
 export DEVON_IDE_HOME=${PWD}
 
+function load_properties() {
+  if ! [ -f "${1}" ]
+  then
+    return
+  fi
+  local key
+  local value
+  while IFS='=' read -r key value
+  do
+    if [ -n "${value}" ] && [ "${key:0:1}" != "#" ]
+    then
+      if [ "${value:0:1}" = "~" ]
+      then
+        value=${HOME}${value:1}
+      fi
+      eval ${key}=${value}
+    fi
+  done < "${1}"
+}
+
 # load and setup configuration
-source "${DEVON_IDE_HOME}/scripts/variables"
-if [ -f "${DEVON_IDE_HOME}/variables" ]
-then
-  source "${DEVON_IDE_HOME}/variables"
-fi
+load_properties "${DEVON_IDE_HOME}/scripts/devon.properties"
+load_properties "${DEVON_IDE_HOME}/devon.properties"
 # copy defaults
 if [ ! -d "${DEVON_IDE_HOME}/conf" ]
 then
@@ -17,32 +34,31 @@ then
 fi
 if [ -d "${SETTINGS_PATH}" ]
 then
-  if [ -f "${SETTINGS_PATH}/devon/variables" ]
+  load_properties "${SETTINGS_PATH}/devon/devon.properties"
+  if ! [ -f "${SETTINGS_PATH}/devon/devon.properties" ]
   then
-    source "${SETTINGS_PATH}/devon/variables"
-  else
     echo
     echo "*** ATTENTION ***"
-    echo "Your devon-ide settings at ${SETTINGS_PATH} are missing project-specific variables."
-    echo "Please create this file at ${SETTINGS_PATH}/devon/variables"
+    echo "Your devon-ide settings at ${SETTINGS_PATH} are missing project-specific devon.properties."
+    echo "Please create this file at ${SETTINGS_PATH}/devon/devon.properties"
     echo "You can get a template from here:"
-    echo "https://github.com/devonfw/devon-ide/blob/master/settings/src/main/settings/devon/variables"
+    echo "https://github.com/devonfw/devon-ide/blob/master/settings/src/main/settings/devon/devon.properties"
   fi
-  if [ ! -f "${DEVON_IDE_HOME}/conf/variables" ]
+  if ! [ -f "${DEVON_IDE_HOME}/conf/devon.properties" ]
   then
-    if [ -f "${SETTINGS_PATH}/devon/conf/variables" ]
+    if [ -f "${SETTINGS_PATH}/devon/conf/devon.properties" ]
     then
-      cp "${SETTINGS_PATH}/devon/conf/variables" "${DEVON_IDE_HOME}/conf/"
+      cp "${SETTINGS_PATH}/devon/conf/devon.properties" "${DEVON_IDE_HOME}/conf/"
     else
       echo
       echo "*** ATTENTION ***"
-      echo "Your devon-ide settings at ${SETTINGS_PATH} are missing a variables template."
-      echo "Please create this file at ${SETTINGS_PATH}/devon/conf/variables"
+      echo "Your devon-ide settings at ${SETTINGS_PATH} are missing a devon.properties template."
+      echo "Please create this file at ${SETTINGS_PATH}/devon/conf/devon.properties"
       echo "You can get a template from here:"
-      echo "https://github.com/devonfw/devon-ide/blob/master/settings/src/main/settings/devon/conf/variables"
+      echo "https://github.com/devonfw/devon-ide/blob/master/settings/src/main/settings/devon/conf/devon.properties"
     fi
   fi
-elif [ "${1}" != "ide" ] || [ "${2}" != "setup" ]
+elif [ "${1}" != "ide" ] || [ "${2}" != "setup" ]
 then
   echo
   echo "*** ATTENTION ***"
@@ -130,9 +146,8 @@ then
 fi
 
 # load user settings late so variables like M2_REPO can be overriden
-if [ -f "${DEVON_IDE_HOME}/conf/variables" ]
-then
-  source "${DEVON_IDE_HOME}/conf/variables"
-fi
+load_properties "${DEVON_IDE_HOME}/conf/devon.properties"
+
+unfunction load_properties
 
 export PATH
