#53: release support and according improvements to build commandlets

diff --git a/scripts/src/main/resources/scripts/functions b/scripts/src/main/resources/scripts/functions
--- a/scripts/src/main/resources/scripts/functions
+++ b/scripts/src/main/resources/scripts/functions
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 # Functions to be reused in devon-ide commands. Will actually be sourced,
 # hash bang only for filetype detection and editor syntax support
 
@@ -23,7 +23,7 @@ function doFail() {
 function doResult() {
   if [ "${2}" = 0 ]
   then
-    echo "Succeeded to ${1}"
+    doEcho "Succeeded to ${1}"
   else
     if [ -z "$2" ]
     then
@@ -48,7 +48,7 @@ function doRunCommand() {
       doFail "Working directory ${3} does not exist."
     fi
   fi
-  echo "Running command: ${1}"
+  doEcho "Running command: ${1}"
   eval ${1}
   result=${?}
   if [ -n "${3}" ]
@@ -65,46 +65,19 @@ function doRunCommand() {
   doResult "${message}" ${result}
 }
 
-# $1: force option
 function doIsForce() {
-  if [ "${1}" = "-f" ] || [ "${1}" = "force" ] || [ "${1}" = "--force" ]
-  then
-    return
-  fi
-  return 255
+  [ -n "${force}" ]
+  return
 }
 
-# $1: optional spaces for indendation
-function doForceHelp() {
-  echo "-f | --force | force ${1}force proceeding even in case of warnings."
-}
-
-# $1: batch option (non interactive mode)
 function doIsBatch() {
-  if [ "${1}" = "-b" ] || [ "${1}" = "batch" ] || [ "${1}" = "--batch" ]
-  then
-    return
-  fi
-  return 255
+  [ -n "${batch}" ]
+  return
 }
 
-# $1: optional spaces for indendation
-function doBatchHelp() {
-  echo "-b | --batch | batch ${1}run in non-interactive mode (do not ask any questions)."
-}
-
-# $1: quiet option
 function doIsQuiet() {
-  if [ "${1}" = "-q" ] || [ "${1}" = "quiet" ] || [ "${1}" = "--quiet" ]
-  then
-    return
-  fi
-  return 255
-}
-
-# $1: optional spaces for indendation
-function doQuietHelp() {
-  echo "-q | --quiet | quiet ${1}be quiet and avoid output."
+  [ -n "${quiet}" ]
+  return
 }
 
 # $1: basename of folder
@@ -124,15 +97,62 @@ function doIsIgnoredFolder() {
   return 255
 }
 
-# $1: quiet option (-q, --quiet, quiet) or anything else to echo
-# $2+: messages to output
+# $@: messages to output
 function doEcho() {
-  if doIsQuiet "${1}"
+  if doIsQuiet
   then
     return
   fi
   shift
   echo -e ${@}
+}
+
+# $@: warning message
+function doWarning() {
+  echo -e "WARNING: ${@}"
+}
+
+# $@: warning message
+function doConfirmWarning() {
+  doWarning ${@}
+  echo
+  doAskToContinue
+}
+
+# $1: optional message
+# $2: if 'return' will return with 255 otherwise exit if not continued
+function doAskToContinue() {
+  if [ -n "${1}" ]
+  then
+    doEcho "${1}"
+  fi
+  if [ -n "${force}" ]
+  then
+    return
+  fi
+  if [ -z "${batch}" ] 
+  then
+    local answer
+    while true
+    do
+      read -p "Do you want to continue? (yes/no) " answer
+      if [ "${answer}" = "yes" ] || [ -z "${answer}" ]
+      then
+        return
+      elif [ "${answer}" = "no" ]
+      then
+        doEcho "Do not continue..."
+        if [ "${2}" = "return" ]
+        then
+          return 255
+        else
+          exit 255
+        fi
+      else
+        echo "Please answer yes or no (or hit return for yes)."
+      fi
+    done
+  fi
 }
 
 function doLogo() {
@@ -179,9 +199,13 @@ function doLicenseAgreement() {
     echo "${DEVON_IDE_HOME}/TERMS_OF_USE.adoc"
     echo "https://github.com/devonfw/devon-ide/wiki/license"
     echo
+    if doIsBatch
+    then
+      doFail "You need to accept these terms of use and all license agreements. Please rerun in interactive (non-batch) mode."
+    fi
     while true
     do
-      read -p "Do you accept this terms of use and all license agreements? (yes/no) " answer
+      read -p "Do you accept these terms of use and all license agreements? (yes/no) " answer
       case "${answer}" in
         yes)
           echo -e "On `date +"%Y-%m-%d"` at `date +"%H:%M:%S"` you accepted the devon-ide terms of use.\nhttps://github.com/devonfw/devon-ide/wiki/license" > ~/.devon/.license.agreement
@@ -199,6 +223,10 @@ function doLicenseAgreement() {
 # ${1}: devon command name
 # ${n+1}: additional args
 function doDevonCommand() {
+  if [ -z "${1}" ]
+  then
+    doFail "Command is required and can not be omitted!"
+  fi
   local command_name="${1}"
   local command="${DEVON_IDE_HOME}/scripts/command/${1}"
   if [ ! -e "${command}" ]
@@ -209,18 +237,19 @@ function doDevonCommand() {
     echo "Not found at ${command}"
     echo "Please check your DEVON_IDE_TOOLS variable:"
     echo "${DEVON_IDE_TOOLS}"
+    return 255
   else
     if [ ! -x "${command}" ]
     then
-      echo "Command ${1} is not executable. Trying to repair..."
+      doEcho "Command ${1} is not executable. Trying to repair..."
       chmod a+x "${command}"
     fi
     shift
-    "${command}" ${@}
+    "${command}" ${force} ${quiet} ${batch} -- ${@}
     result=${?}
     if [ ${result} != 0 ]
     then
-      echo "ERROR: command '${command_name} ${@}' failed with exit code ${result}"
+      doEcho "ERROR: command '${command_name} ${@}' failed with exit code ${result}"
       exit ${result}
     fi
   fi
@@ -232,15 +261,20 @@ function doDownload() {
   local target_dir=~/Downloads
   local filename="${1/*\//}"
   local target="${target_dir}/${filename}"
-  if [ -f "${target}" ]
+  if [ -f "${target}" ] && [ -z "${force}" ]
   then
-    echo "Artifact already exists at ${target}"
-    echo "To force update please delete the file and run again."
-    return -1
+    doEcho "Artifact already exists at ${target}"
+    doEcho "To force update please delete the file and run again."
+    return 255
   fi
   mkdir -p "${target_dir}"
-  echo "Downloading ${filename} from ${1}"
-  curl -fL "${1}" -o "${target_dir}/${filename}"
+  doEcho "Downloading ${filename} from ${1}"
+  local curl_opt=""
+  if [ -n "${quiet}" ]
+  then
+    curl_opt="--silent"
+  fi
+  curl ${curl_opt} -fL "${1}" -o "${target_dir}/${filename}"
   result=${?}
   if [ "${result}" != 0 ]
   then
@@ -497,6 +531,10 @@ function doGitPullOrClone() {
 # $3: optional archive folder to rename
 # $4: optional sub-folder to extract to
 function doInstall() {
+  if [ -z "${1}" ]
+  then
+    doFail "Missing target path for installation: ${@}"
+  fi
   local dir=${1/*\//}
   if [ "${2/*\.//.}" = ".git" ]
   then
@@ -574,7 +612,7 @@ function doCreateIdeScript() {
     echo -e "@echo off\r\npushd %%~dp0\r\ncd workspaces/${WORKSPACE}\r\ncall devon.bat ${1}\r\npopd" > ${1}-${WORKSPACE}.bat
     echo "Created script ${1}-${WORKSPACE}.bat"
   else
-    echo -e "#!/bin/bash\ncd \`dirname \${0}\`\ncd workspaces/${WORKSPACE}\nsource ${DEVON_IDE_HOME}/scripts/devon ${1}" > ${1}-${WORKSPACE}
+    echo -e "#!/usr/bin/env bash\ncd \`dirname \${0}\`\ncd workspaces/${WORKSPACE}\nsource ${DEVON_IDE_HOME}/scripts/devon ${1}" > ${1}-${WORKSPACE}
     chmod a+x ${1}-${WORKSPACE}
     echo "Created script ${1}-${WORKSPACE}"
   fi
@@ -698,3 +736,26 @@ doLoadProperties "${DEVON_IDE_HOME}/devon.properties"
 doLoadProperties "${SETTINGS_PATH}/devon/devon.properties"
 doLoadProperties "${DEVON_IDE_HOME}/conf/devon.properties"
 
+batch=""
+force=""
+quiet=""
+while [ -n "${1}" ]
+do
+  if [ "${1}" = "--" ]
+  then
+    shift
+    break
+  elif [ "${1}" = "-b" ] || [ "${1}" = "--batch" ]
+  then
+    batch="${1}"
+  elif [ "${1}" = "-f" ] || [ "${1}" = "--force" ]
+  then
+    force="${1}"
+  elif [ "${1}" = "-q" ] || [ "${1}" = "--quiet" ]
+  then
+    quiet="${1}"
+  else
+    break
+  fi
+  shift
+done
