add test for windows setup.bat and devon.bat

diff --git a/scripts/src/test/bash/functions-test b/scripts/src/test/bash/functions-test
--- a/scripts/src/test/bash/functions-test
+++ b/scripts/src/test/bash/functions-test
@@ -6,6 +6,16 @@ function doCommandTest()  {
   exit "${?}"
 }
 
+function doExtract() {
+  if [ -f "${1}" ]
+  then
+    tar xfz "${1}" || exit 1
+  else
+    echo "Could not find and extract release ${1}"
+    exit 1
+  fi
+}
+
 # $@: success message
 function doSuccess() {
   echo -e "\033[92m${*}\033[39m"
