test upgrade

diff --git a/scripts/src/test/bash/test-sfcommands b/scripts/src/test/bash/test-sfcommands
--- a/scripts/src/test/bash/test-sfcommands
+++ b/scripts/src/test/bash/test-sfcommands
@@ -11,6 +11,7 @@ success=0
 failure=0
 failures=()
 total=0
+failedTest=false
 cd ../test-setup
 CLI="${PWD}/scripts/devon"
 rm -f -r software
@@ -49,28 +50,37 @@ else
   do
     echo "${i}"
   done
+  failedTest=true
 fi
 
 echo "Running test for EXTRA_JAVA_VERSION"
 export EXTRA_JAVA_VERSION=8u292b10
-"${CLI}" java setup
+"${CLI}" java setup &> /dev/null
 if [[ -d "../../software/extra/java" ]] 
 then
-  echo "[SUCCESS] EXTRA_JAVA_VERSION."
+  echo "[SUCCESS] EXTRA_JAVA_VERSION"
 else
-  echo "[FAILURE] EXTRA_JAVA_VERSION."
+  echo "[FAILURE] EXTRA_JAVA_VERSION"
+  failedTest=true
 fi
 
 echo "Running test for JAVA_VERSION"
 export JAVA_VERSION=18.0.2_9
-"${CLI}" java setup
+"${CLI}" java setup &> /dev/null
 CURRENT_JAVA_VERSION=$(cat "../../software/java/.devon.software.version")
 if [[ "${JAVA_VERSION}" == "${CURRENT_JAVA_VERSION}" ]]
 then
-  echo "[SUCCESS] JAVA_VERSION."
+  echo "[SUCCESS] JAVA_VERSION"
 else
-  echo "[FAILURE] JAVA_VERSION."
+  echo "[FAILURE] JAVA_VERSION"
+  failedTest=true
 fi
 
+if "${failedTest}"
+then
+  exit 1
+else 
+  exit 0
+fi
 
 
