update latest script for distribution

diff --git a/scripts/src/main/resources/create-or-update-workspace b/scripts/src/main/resources/create-or-update-workspace
--- a/scripts/src/main/resources/create-or-update-workspace
+++ b/scripts/src/main/resources/create-or-update-workspace
@@ -1,6 +1,6 @@
 #!/bin/bash
-set -e
 
+set -e
 cd `dirname $0`
 
 if [ -n $1 ]; then
@@ -9,43 +9,44 @@ fi
 
 . scripts/environment-project
 
-if [ ! -d $SOFTWARE_PATH ]; then
+if [ ! -d $OASP_PROJECT_HOME/$OFTWARE_PATH ]; then
     echo "Could not find folder $SOFTWARE_PATH"
     echo "If you want to change its name see the variables"
     echo "Execution aborted"
     exit 1
 fi
-if [ ! -d $WORKSPACES_PATH ]; then
-    echo "Could not find folder $WORKSPACES_PATH"
+if [ ! -d $OASP_PROJECT_HOME/$WORKSPACES_PATH ]; then
+    echo "Could not find folder $OASP_PROJECT_HOME/$WORKSPACES_PATH"
     echo "If you want to change its name see the variables"
     echo "Execution aborted"
     exit 1
 fi
-if [ ! -d $WORKSPACE_PATH ]; then
-    echo "Could not find workspace $WORKSPACE_PATH"
+if [ ! -d $OASP_PROJECT_HOME/$WORKSPACE_PATH ]; then
+    echo "Could not find workspace $OASP_PROJECT_HOME/$WORKSPACE_PATH"
     echo "Execution aborted"
     exit 1
 fi
-if [ ! -d $SETTINGS_PATH ]; then
-    echo "Could not find folder $SETTINGS_PATH"
+if [ ! -d $OASP_PROJECT_HOME/$SETTINGS_PATH ]; then
+    echo "Could not find folder $OASP_PROJECT_HOME/$SETTINGS_PATH"
     echo "If you want to change its name see the variables"
     echo "Execution aborted"
     exit 1
 fi
 
 
-if [ ! -e $CONF_PATH/.m2 ]; then
-    mkdir -p $CONF_PATH/.m2
+if [ ! -e $OASP_PROJECT_HOME/$CONF_PATH/.m2 ]; then
+    mkdir -p $OASP_PROJECT_HOME/$CONF_PATH/.m2
 fi
-if [ ! -e $CONF_PATH/.m2/settings.xml ]; then
-    cp $SETTINGS_PATH/maven/settings.xml $CONF_PATH/.m2/settings.xml
+if [ ! -e $OASP_PROJECT_HOME/$CONF_PATH/.m2/settings.xml ]; then
+    cp $OASP_PROJECT_HOME/$SETTINGS_PATH/maven/settings.xml $OASP_PROJECT_HOME/$CONF_PATH/.m2/settings.xml
     echo "Copied $SETTINGS_PATH/maven/settings.xml to $CONF_PATH/.m2/settings.xml"
+    cp $OASP_PROJECT_HOME/$SETTINGS_PATH/version/settings.json $OASP_PROJECT_HOME/$CONF_PATH/settings.json
+    echo "Copied $SETTINGS_PATH/version/settings.json to $CONF_PATH/settings.json"
 fi
 
 # TODO: Port subversion config
 
 
-ECLIPSE_TEMPLATES_PATH=$SETTINGS_PATH\eclipse\workspace
 if [ ! -d $ECLIPSE_TEMPLATES_PATH ]; then
     echo "Could not find folder $ECLIPSE_TEMPLATES_PATH"
     echo "Execution aborted"
@@ -65,7 +66,7 @@ fi
 #WORKSPACE_PATH=$WORKSPACE_REL_PATH
 REPLACEMENT_PATTERNS_PATH=$ECLIPSE_REPLACEMENT_PATTERNS_PATH
 
-java -jar $SCRIPTS_PATH/$IDE_CONFIGURATOR -t "$ECLIPSE_TEMPLATES_PATH" -w "$WORKSPACE_PATH" -v "$REPLACEMENT_PATTERNS_PATH" -u
+java -jar $SCRIPTS_PATH/$ECLIPSE_CONFIGURATOR -u
 echo "Eclipse preferences for workspace $WORKSPACE have been created/updated"
 
 if [ ! -e "eclipse-$WORKSPACE" ]
