#31: devon-ide is going to rock the world

diff --git a/scripts/src/main/resources/scripts/command/eclipse b/scripts/src/main/resources/scripts/command/eclipse
--- a/scripts/src/main/resources/scripts/command/eclipse
+++ b/scripts/src/main/resources/scripts/command/eclipse
@@ -51,9 +51,9 @@ do
 done
 
 if [ ! -d "${WORKSPACE_PATH}" ]; then
-    echo "Could not find folder '${WORKSPACE_PATH}' (from variable WORKSPACE_PATH)"
-    echo "Execution aborted"
-    exit 1
+  echo "Could not find folder '${WORKSPACE_PATH}' (from variable WORKSPACE_PATH)"
+  echo "Execution aborted"
+  exit 1
 fi
 
 ECLIPSE_TEMPLATES_PATH=${SETTINGS_PATH}/eclipse/workspace
