Import and checkout working (not run in sequence yet)

diff --git a/scripts/src/main/resources/scripts/command/eclipse b/scripts/src/main/resources/scripts/command/eclipse
--- a/scripts/src/main/resources/scripts/command/eclipse
+++ b/scripts/src/main/resources/scripts/command/eclipse
@@ -1,6 +1,7 @@
 #!/usr/bin/env bash
 # shellcheck source=scripts/functions
 source "$(dirname "${0}")"/../functions
+L_PWD=`pwd`
 cd "${DEVON_IDE_HOME}" || exit 255
 
 # $1: plugin feature group ID
@@ -158,10 +159,29 @@ function doStartEclipse() {
   fi
 }
 
+function doCheckAndInstallGroovy {
+  if [ ! -f "${M2_REPO}//org/codehaus/groovy/groovy-ant/3.0.0/groovy-ant-3.0.0.jar" -o ! -f "${M2_REPO}//org/codehaus/groovy/groovy/3.0.0/groovy-3.0.0.jar" ]; then
+    echo "Groovy not found. Installing..."
+    doRunCommand "mvn org.apache.maven.plugins:maven-dependency-plugin:2.10:get -Dartifact=org.codehaus.groovy:groovy-ant:3.0.0:pom -DremoteRepositories=https://mvnrepository.com"
+    doRunCommand "mvn org.apache.maven.plugins:maven-dependency-plugin:2.10:get -Dartifact=org.codehaus.groovy:groovy:3.0.0:pom -DremoteRepositories=https://mvnrepository.com"
+  fi
+}
 
 function doImportEclipse() {
-  echo "Starting eclipse project import for workspace ${WORKSPACE} at ${WORKSPACE_PATH}"
-  export DEVON_IMPORT_CONFIG=${WORKSPACE_PATH}/import.properties
+  if [ -z "${1}" ]
+  then
+    doFail "Parameter \"path\" is missing."
+  fi
+  doCheckAndInstallGroovy
+  if [[ "${1}" = /* ]]
+  then
+    export DEVON_IMPORT_PATH="${1}"
+  else
+    # Path is relative make it absolute
+    export DEVON_IMPORT_PATH="${L_PWD}/${1}"
+  fi  
+  export DEVON_IMPORT_WORKINGSET="${2}"
+  echo "Starting eclipse import for ${DEVON_IMPORT_PATH} into workspace ${WORKSPACE} at ${WORKSPACE_PATH}"
   if doIsWindows
   then
     # shellcheck disable=SC2086
@@ -170,7 +190,6 @@ function doImportEclipse() {
     # shellcheck disable=SC2086
     "${ECLIPSE_HOME}/eclipse" -clean -application org.eclipse.ant.core.antRunner -buildfile "${DEVON_IDE_HOME}/scripts/lib_script/import.xml" -data "${WORKSPACE_PATH}" -keyring ~/.eclipse/.keyring -vm "${JAVA_HOME}/bin/java" -vmargs ${ECLIPSE_VMARGS}
   fi
-  export DEVON_IMPORT_CONFIG=
 }
 
 # CLI
@@ -179,14 +198,15 @@ then
   echo "Manage Eclipse IDE and workspace."
   echo
   echo "Arguments:"
-  echo " --all                    if provided as first arg then to command will be invoked for each workspace"
-  echo " setup                    setup Eclipse (install or update)"
-  echo " add-plugin «id» [«url»]  install an additional plugin"
-  echo " run | start              launch Eclipse IDE (default if no argument is given)"
-  echo " ws-up[date]              update eclipse workspace"
-  echo " ws-re[verse]             reverse merge changes from workspace into settings"
-  echo " ws-reverse-add           reverse merge adding new properties"
-  echo " create-script            create eclipse-${WORKSPACE} script if not already exists"
+  echo " --all                           if provided as first arg then to command will be invoked for each workspace"
+  echo " setup                           setup Eclipse (install or update)"
+  echo " add-plugin «id» [«url»]         install an additional plugin"
+  echo " run | start                     launch Eclipse IDE (default if no argument is given)"
+  echo " ws-up[date]                     update eclipse workspace"
+  echo " ws-re[verse]                    reverse merge changes from workspace into settings"
+  echo " ws-reverse-add                  reverse merge adding new properties"
+  echo " create-script                   create eclipse-${WORKSPACE} script if not already exists"
+  echo " import «path» [«workingsets»]   import projects in «path» into current workspace. «workingsets» comma-separated list of workingsets (no spaces between ,), eg: ./myproject ws1,ws2"
   exit
 fi
 ECLIPSE_HOME="${DEVON_IDE_HOME}/software/eclipse"
@@ -229,7 +249,8 @@ do
     exit ${?}
   elif [ "${1}" = "import" ] 
   then
-    doImportEclipse
+    doImportEclipse ${2} ${3}
+    exit ${?}
   else
     doFail "Unknown argument: ${1}"
   fi
