#175: automated git checkout and eclipse import (#353)

diff --git a/scripts/src/main/resources/scripts/command/eclipse b/scripts/src/main/resources/scripts/command/eclipse
--- a/scripts/src/main/resources/scripts/command/eclipse
+++ b/scripts/src/main/resources/scripts/command/eclipse
@@ -1,6 +1,7 @@
 #!/usr/bin/env bash
 # shellcheck source=scripts/functions
 source "$(dirname "${0}")"/../functions
+L_PWD=$(pwd)
 cd "${DEVON_IDE_HOME}" || exit 255
 
 # $1: plugin feature group ID
@@ -158,20 +159,54 @@ function doStartEclipse() {
   fi
 }
 
+function doCheckAndInstallGroovy() {
+  local groovy_version=3.0.1
+  if [ ! -f "${M2_REPO}/org/codehaus/groovy/groovy-ant/${groovy_version}/groovy-ant-${groovy_version}.jar" ] || [ ! -f "${M2_REPO}/org/codehaus/groovy/groovy/${groovy_version}/groovy-${groovy_version}.jar" ]; then
+    echo "Groovy not found. Installing version ${groovy_version} in Maven repository ${M2_REPO}..."
+    doRunCommand "mvn org.apache.maven.plugins:maven-dependency-plugin:2.10:get -Dartifact=org.codehaus.groovy:groovy-ant:${groovy_version}:jar -DremoteRepositories=https://mvnrepository.com"
+  fi
+}
+
+function doImportEclipse() {
+  if [ -z "${1}" ]
+  then
+    doFail "Parameter \"path\" is missing."
+  fi
+  doCheckAndInstallGroovy
+  if [[ "${1}" = /* ]]
+  then
+    importPath="${1}"
+  else
+    # Path is relative make it absolute
+    importPath="${L_PWD}/${1}"
+  fi  
+  importWorkingSets="${2}"
+  echo "Starting eclipse import for ${importPath} into workspace ${WORKSPACE} at ${WORKSPACE_PATH}"
+  if doIsWindows
+  then
+    # shellcheck disable=SC2086
+    start "eclipse" /B "${ECLIPSE_HOME}/eclipsec" -clean -application org.eclipse.ant.core.antRunner -buildfile "${DEVON_IDE_HOME}/scripts/lib_script/import.xml" -data "${WORKSPACE_PATH}" -keyring ~/.eclipse/.keyring -vm "${JAVA_HOME}/bin/javaw" -vmargs -DdevonImportPath="${importPath}" -DdevonImportWorkingSets="${importWorkingSets}" ${ECLIPSE_VMARGS}
+  else
+    # shellcheck disable=SC2086
+    "${ECLIPSE_HOME}/eclipse" -clean -application org.eclipse.ant.core.antRunner -buildfile "${DEVON_IDE_HOME}/scripts/lib_script/import.xml" -data "${WORKSPACE_PATH}" -keyring ~/.eclipse/.keyring -vm "${JAVA_HOME}/bin/java" -vmargs -DdevonImportPath="${importPath}" -DdevonImportWorkingSets="${importWorkingSets}" ${ECLIPSE_VMARGS} 
+  fi
+}
+
 # CLI
 if [ "${1}" = "-h" ] || [ "${1}" = "help" ]
 then
   echo "Manage Eclipse IDE and workspace."
   echo
   echo "Arguments:"
-  echo " --all                    if provided as first arg then to command will be invoked for each workspace"
-  echo " setup                    setup Eclipse (install or update)"
-  echo " add-plugin «id» [«url»]  install an additional plugin"
-  echo " run | start              launch Eclipse IDE (default if no argument is given)"
-  echo " ws-up[date]              update eclipse workspace"
-  echo " ws-re[verse]             reverse merge changes from workspace into settings"
-  echo " ws-reverse-add           reverse merge adding new properties"
-  echo " create-script            create eclipse-${WORKSPACE} script if not already exists"
+  echo " --all                           if provided as first arg then to command will be invoked for each workspace"
+  echo " setup                           setup Eclipse (install or update)"
+  echo " add-plugin «id» [«url»]         install an additional plugin"
+  echo " run | start                     launch Eclipse IDE (default if no argument is given)"
+  echo " ws-up[date]                     update eclipse workspace"
+  echo " ws-re[verse]                    reverse merge changes from workspace into settings"
+  echo " ws-reverse-add                  reverse merge adding new properties"
+  echo " create-script                   create eclipse-${WORKSPACE} script if not already exists"
+  echo " import «path» [«workingsets»]   import projects in «path» into current workspace. «workingsets» comma-separated list of workingsets (no spaces between ,), eg: ./myproject ws1,ws2"
   exit
 fi
 ECLIPSE_HOME="${DEVON_IDE_HOME}/software/eclipse"
@@ -211,6 +246,10 @@ do
   then
     shift
     doAddPlugin "${@}"
+    exit ${?}
+  elif [ "${1}" = "import" ] 
+  then
+    doImportEclipse "${2}" "${3}"
     exit ${?}
   else
     doFail "Unknown argument: ${1}"
