#1164: fixed jenkins stop command added new JENKINS_HOME environment variable to devon.properties renamed JENKINS_HOME in jenkins script to JENKINS_CLI_HOME added jenkins home folder creation to doSetup added override of java user.home to each java command of jenkins added first version of admin password retrieval

diff --git a/scripts/src/main/resources/scripts/command/jenkins b/scripts/src/main/resources/scripts/command/jenkins
--- a/scripts/src/main/resources/scripts/command/jenkins
+++ b/scripts/src/main/resources/scripts/command/jenkins
@@ -12,26 +12,30 @@ fi
 
 # shellcheck source=scripts/functions
 source "$(dirname "${0}")"/../functions
-JENKINS_HOME="${DEVON_IDE_HOME}/software/jenkins"
-TOOL_VERSION_COMMAND="java -jar '${JENKINS_HOME}/jenkins.war' --version"
+JENKINS_CLI_HOME="${DEVON_IDE_HOME}/software/jenkins"
+TOOL_VERSION_COMMAND="java -Duser.home=${JENKINS_HOME} -jar '${JENKINS_CLI_HOME}/jenkins.war' --version"
 # shellcheck source=scripts/commandlet-cli
 source "$(dirname "${0}")"/../commandlet-cli
 
 # $1: optional setup
 function doSetup() {
   doDevonCommand java setup silent
-  if [ -d "${JENKINS_HOME}" ]
+  if [ -d "${JENKINS_CLI_HOME}" ]
   then
     if [ "${1}" != "silent" ]
     then
-      echo "Jenkins is already installed at ${JENKINS_HOME}"
+      echo "Jenkins is already installed at ${JENKINS_CLI_HOME}"
     fi
   else
+    if [ ! -f "${JENKINS_HOME}" ]
+    then
+      doRunCommand "mkdir '${JENKINS_HOME}'"
+    fi
     # shellcheck disable=SC2034
     TOOL_VERSION_COMMAND="-"
     doInstall "jenkins" "${JENKINS_VERSION}" "" "" "" "" "noUnpack" "" "" "jenkins.war"
     local cwd="${PWD}"
-    cd "${JENKINS_HOME}" || exit 255
+    cd "${JENKINS_CLI_HOME}" || exit 255
     local version=${JENKINS_VERSION}
     if [ -z "${JENKINS_VERSION}" ]
     then
@@ -44,21 +48,26 @@ function doSetup() {
   fi
   if [ "${1}" != "silent" ] && ! doIsQuiet
   then
-    doRunCommand "java -jar '${JENKINS_HOME}/jenkins.war' --version" "verify installation of Jenkins"
+    doRunCommand "java -Duser.home=${JENKINS_HOME} -jar '${JENKINS_CLI_HOME}/jenkins.war' --version" "verify installation of Jenkins"
   fi
 }
 
 function doStart() {
   doSetup silent
-  doRunCommand "java -jar '${JENKINS_HOME}/jenkins.war' --httpPort=${JENKINS_PORT:-9999} ${JENKINS_OPTS} || echo -e 'Jenkins could not be started.\nIf you see \"Address already in use\" error above this only means it was already running.' &"
-  sleep 15  
+  doRunCommand "java -Duser.home=${JENKINS_HOME} -jar '${JENKINS_CLI_HOME}/jenkins.war' --httpPort=${JENKINS_PORT:-9999} ${JENKINS_OPTS} || echo -e 'Jenkins could not be started.\nIf you see \"Address already in use\" error above this only means it was already running.' &"
+  sleep 15
   echo
   echo "Jenkins is running on http://localhost:${JENKINS_PORT:-9999}"
 }
 
 function doJenkinsCli() {
-  echo java -jar "${JENKINS_HOME}/jenkins-cli.jar" -s "http://localhost:${JENKINS_PORT:-9999}" -auth "${JENKINS_ADMIN_LOGIN:-admin}:${JENKINS_ADMIN_PASSWORD:-admin}" "${@}"
-  java -jar "${JENKINS_HOME}/jenkins-cli.jar" -s "http://localhost:${JENKINS_PORT:-9999}" -auth "${JENKINS_ADMIN_LOGIN:-admin}:${JENKINS_ADMIN_PASSWORD:-admin}" "${@}"
+  local admin_password="admin"
+  if [ -f "${JENKINS_HOME}/secrets/initialAdminPassword" ]
+  then
+    admin_password="`cat ${JENKINS_HOME}/secrets/initialAdminPassword`"
+  fi
+  echo java -Duser.home=${JENKINS_HOME} -jar "${JENKINS_CLI_HOME}/jenkins-cli.jar" -s "http://localhost:${JENKINS_PORT:-9999}" -auth "${JENKINS_ADMIN_LOGIN:-admin}:${JENKINS_ADMIN_PASSWORD:-${admin_password}}" "${@}"
+  java -Duser.home=${JENKINS_HOME} -jar "${JENKINS_CLI_HOME}/jenkins-cli.jar" -s "http://localhost:${JENKINS_PORT:-9999}" -auth "${JENKINS_ADMIN_LOGIN:-admin}:${JENKINS_ADMIN_PASSWORD:-${admin_password}}" "${@}"
 }
 
 function doStop() {
@@ -76,7 +85,7 @@ function doAdd() {
   then
     doFail "Could not find Jenkinsfile (${JENKINSFILE})."
   fi
-  sed "s~@GIT@~file://${PWD}~" "${DEVON_IDE_HOME}/scripts/templates/jenkins/project.xml" | sed "s~@UUID@~$(head -c 20 /dev/random | base64)~" | java -jar "${JENKINS_HOME}/jenkins-cli.jar" -s "http://localhost:${JENKINS_PORT:-9999}" -auth "${JENKINS_ADMIN_LOGIN:-admin}:${JENKINS_ADMIN_PASSWORD:-admin}" create-job "$(basename "${PWD}")"
+  sed "s~@GIT@~file://${PWD}~" "${DEVON_IDE_HOME}/scripts/templates/jenkins/project.xml" | sed "s~@UUID@~$(head -c 20 /dev/random | base64)~" | java -jar "${JENKINS_CLI_HOME}/jenkins-cli.jar" -s "http://localhost:${JENKINS_PORT:-9999}" -auth "${JENKINS_ADMIN_LOGIN:-admin}:${JENKINS_ADMIN_PASSWORD:-admin}" create-job "$(basename "${PWD}")"
 }
 
 function doRemove() {
